name: Ejercicio 3 Parte 1

on:
  push:
    branches:
      - main

jobs:
  ej1:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Instalar pytest
        run: pip install pytest
      - name: Ejecutar tests
        run: pytest test.py
